# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 06:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('CC', 'Cedula de ciudadan\xeda'), ('CE', 'Cedula de Extranjer\xeda'), ('NIT', 'NIT'), ('Pst', 'Pasaporte'), ('CD', 'Carnet Dipom\xe1tico')], default='CC', max_length=20, verbose_name='Tipo de documento')),
                ('document_number', models.CharField(max_length=30, verbose_name='N\xfamero de Identificaci\xf3n')),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'LGTBI')], default='M', max_length=10, verbose_name='G\xe9nero')),
                ('phone', models.CharField(max_length=30, verbose_name='Tel\xe9fono')),
                ('address', models.CharField(max_length=30, verbose_name='Direcci\xf3n')),
                ('availability_monday', models.BooleanField(default=False, verbose_name='Disponibilidad lunes')),
                ('availability_tuesday', models.BooleanField(default=False, verbose_name='Disponibilidad martes')),
                ('availability_wednesday', models.BooleanField(default=False, verbose_name='Disponibilidad mi\xe9rcoles')),
                ('availability_thursday', models.BooleanField(default=False, verbose_name='Disponibilidad jueves')),
                ('availability_friday', models.BooleanField(default=False, verbose_name='Disponibilidad viernes')),
                ('availability_saturday', models.BooleanField(default=False, verbose_name='Disponibilidad sabado')),
                ('availability_sunday', models.BooleanField(default=False, verbose_name='Disponibilidad domingo')),
                ('certified', models.BooleanField(default=False, verbose_name='Certificado')),
                ('service', models.CharField(choices=[('CE', 'Cerrajer\xeda'), ('PLO', 'Plomer\xeda'), ('CAR', 'Carpinter\xeda'), ('ELEC', 'Electricidad'), ('JAR', 'Jardiner\xeda'), ('PIN', 'Pintura'), ('PLA', 'Plagas'), ('TECHO', 'Techos'), ('PAREDES', 'Paredes y Pisos')], default='CE', max_length=15, verbose_name='Servicio')),
                ('role', models.CharField(choices=[('Work', 'Trabajador'), ('Aux', 'Auxiliar')], default='Work', max_length=15, verbose_name='Cargo')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Profile_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('CC', 'Cedula de ciudadan\xeda'), ('CE', 'Cedula de Extranjer\xeda'), ('NIT', 'NIT'), ('Pst', 'Pasaporte'), ('CD', 'Carnet Dipom\xe1tico')], default='CC', max_length=20, verbose_name='Tipo de documento')),
                ('document_number', models.CharField(max_length=30, verbose_name='N\xfamero de Identificaci\xf3n')),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'LGTBI')], default='M', max_length=10, verbose_name='G\xe9nero')),
                ('phone', models.CharField(max_length=30, verbose_name='Tel\xe9fono')),
                ('role', models.CharField(choices=[('Work', 'Trabajador'), ('User', 'Usuario')], default='User', max_length=15, verbose_name='Cargo')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
    ]
