# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 06:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PES_APP', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='service',
        ),
        migrations.AddField(
            model_name='profile',
            name='service_car',
            field=models.BooleanField(default=False, verbose_name='Carpinter\xeda'),
        ),
        migrations.AddField(
            model_name='profile',
            name='service_ce',
            field=models.BooleanField(default=False, verbose_name='Cerrajer\xeda'),
        ),
        migrations.AddField(
            model_name='profile',
            name='service_elec',
            field=models.BooleanField(default=False, verbose_name='Electricidad'),
        ),
        migrations.AddField(
            model_name='profile',
            name='service_jar',
            field=models.BooleanField(default=False, verbose_name='Jardiner\xeda'),
        ),
        migrations.AddField(
            model_name='profile',
            name='service_par',
            field=models.BooleanField(default=False, verbose_name='Paredes y Pisos'),
        ),
        migrations.AddField(
            model_name='profile',
            name='service_pin',
            field=models.BooleanField(default=False, verbose_name='Pintura'),
        ),
        migrations.AddField(
            model_name='profile',
            name='service_pla',
            field=models.BooleanField(default=False, verbose_name='Plagas'),
        ),
        migrations.AddField(
            model_name='profile',
            name='service_plo',
            field=models.BooleanField(default=False, verbose_name='Plomer\xeda'),
        ),
        migrations.AddField(
            model_name='profile',
            name='service_techo',
            field=models.BooleanField(default=False, verbose_name='Techos'),
        ),
    ]
