# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PES_APP', '0002_auto_20170503_0146'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile_user',
            name='address',
            field=models.CharField(blank=True, max_length=30, verbose_name='Direcci\xf3n'),
        ),
        migrations.AddField(
            model_name='profile_user',
            name='city',
            field=models.CharField(blank=True, choices=[('Pei', 'Pereira'), ('Ddas', 'Dosquebradas')], default='Pei', max_length=15, verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='profile_user',
            name='payment',
            field=models.CharField(blank=True, choices=[('Efe', 'Efectivo'), ('Tcred', 'Tarjeta de cr\xe9dito o d\xe9bito')], default='Efe', max_length=15, verbose_name='Pago'),
        ),
    ]
